#!/bin/sh -x
#
# bootstrap by Miroslav Zagorac <mzagorac@haproxy.com>
#
# Generate autotools build system configuration files by running libtoolize,
# aclocal, autoheader, automake, and autoconf.
#
mkdir -p config
libtoolize || exit
aclocal -I m4 || exit
autoheader || exit
automake --add-missing --copy || exit
autoconf || exit

rm -rf autom4te.cache
