/***
 * Copyright 2026 HAProxy Technologies, Miroslav Zagorac <mzagorac@haproxy.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#define OTELC_STATIC_ASSERT_TRACER
#include "include.h"


static otel_nostd::shared_ptr<otel_trace::Tracer> otel_tracer{};


#ifndef OTELC_USE_STATIC_HANDLE

/***
 * NAME
 *   otel_tracer_handle_init - per-thread initialization of tracer handles
 *
 * SYNOPSIS
 *   static int otel_tracer_handle_init(void)
 *
 * ARGUMENTS
 *   This function takes no arguments.
 *
 * DESCRIPTION
 *   Ensures that thread-local otel_span and otel_span_context handles are
 *   allocated for the calling thread.  When OTELC_USE_STATIC_HANDLE is
 *   defined, the handles are constructed automatically by the C++ runtime
 *   and this function is a no-op.  Otherwise the function allocates both
 *   handles on first call per thread.
 *
 * RETURN VALUE
 *   Returns OTELC_RET_OK on success, or OTELC_RET_ERROR if allocation fails.
 */
static int otel_tracer_handle_init(void)
{
	if (OTEL_NULL(otel_span)) {
		otel_span = new(std::nothrow) struct otel_handle<struct otel_span_handle *>();
		if (OTEL_NULL(otel_span))
			return OTELC_RET_ERROR;
	}

	if (OTEL_NULL(otel_span_context)) {
		otel_span_context = new(std::nothrow) struct otel_handle<struct otel_span_context_handle *>();
		if (OTEL_NULL(otel_span_context))
			return OTELC_RET_ERROR;
	}

	return OTELC_RET_OK;
}

#endif /* OTELC_USE_STATIC_HANDLE */


/***
 * NAME
 *   otel_tracer_start_span_with_options - starts a new span with detailed options
 *
 * SYNOPSIS
 *   static struct otelc_span *otel_tracer_start_span_with_options(struct otelc_tracer *tracer, const char *operation_name, const struct otelc_span *parent_span, const struct otelc_span_context *parent_context, const struct timespec *ts_steady, const struct timespec *ts_system, otelc_span_kind_t kind, const struct otelc_span_link *links, size_t links_len)
 *
 * ARGUMENTS
 *   tracer         - tracer instance
 *   operation_name - span name
 *   parent_span    - parent span for the span being started
 *   parent_context - parent span context for the span being started
 *   ts_steady      - a timepoint relative to the monotonic clock epoch
 *   ts_system      - a timepoint relative to the system clock epoch
 *   kind           - span type, can be used to further specify the relationship between the spans
 *   links          - an array of span links to establish at creation time
 *   links_len      - number of elements in the links array
 *
 * DESCRIPTION
 *   Starts a new span with the specified options, including its name, parent
 *   (either a span or a context), timestamps, kind and an array of span links
 *   established at creation time.  This allows for fine-grained control over
 *   span creation, which is essential for accurate distributed tracing.
 *
 *   Unlike AddLink (which requires ABI version 2), links at creation time are
 *   supported by all ABI versions.  Each link references either a span or a
 *   span context and may carry its own set of attributes.  When links is NULL
 *   or links_len is 0, it is not used.
 *
 *   NOTE: otelc_span_kind_t is an autogenerated enum from the OpenTelemetry
 *   C++ headers, defined in include/opentelemetry-c-wrapper/otel_cpp.h.
 *
 * RETURN VALUE
 *   Returns a pointer to the otelc_span structure used to manage the span,
 *   or nullptr in case of an error.
 */
static struct otelc_span *otel_tracer_start_span_with_options(struct otelc_tracer *tracer, const char *operation_name, const struct otelc_span *parent_span, const struct otelc_span_context *parent_context, const struct timespec *ts_steady, const struct timespec *ts_system, otelc_span_kind_t kind, const struct otelc_span_link *links, size_t links_len)
{
	OTEL_LOCK(span, span_context);
	otel_nostd::shared_ptr<otel_context::Context>  parent_maybe{};
	otel_trace::StartSpanOptions                   span_options{};
	struct otelc_span                             *retptr = nullptr;

	OTELC_FUNC("%p, \"%s\", %p, %p, %p, %p, %d", tracer, OTELC_STR_ARG(operation_name), parent_span, parent_context, ts_steady, ts_system, kind);

	if (OTEL_NULL(tracer))
		OTELC_RETURN_PTR(nullptr);
	else if (!OTELC_STR_IS_VALID(operation_name))
		OTEL_TRACER_ERETURN_PTR("Invalid operation name");
	else if (!OTEL_NULL(parent_span) && !OTEL_NULL(parent_context))
		OTEL_TRACER_ERETURN_PTR("Parameters parent_span and parent_context are mutually exclusive");

	auto tracer_ptr = otel_tracer;
	if (OTEL_NULL(tracer_ptr))
		OTEL_TRACER_ERETURN_PTR("Invalid tracer");

#if !defined(OTELC_USE_THREAD_SHARED_HANDLE) && !defined(OTELC_USE_STATIC_HANDLE)
	if (otel_tracer_handle_init() == OTELC_RET_ERROR)
		OTEL_TRACER_ERETURN_PTR(OTEL_ERROR_MSG_ENOMEM("tracer handle"));
#endif

	if (!OTEL_NULL(ts_system))
		span_options.start_system_time = otel_system_timestamp(timespec_to_duration(ts_system));

	if (!OTEL_NULL(ts_steady))
		span_options.start_steady_time = otel_steady_timestamp(timespec_to_duration(ts_steady));

	/* This must align with the otelc_span_kind_t defined in otel_cpp.h. */
	static constexpr otel_trace::SpanKind span_kind_map[] = {
		otel_trace::SpanKind::kInternal, /* UNSPECIFIED */
		otel_trace::SpanKind::kInternal, /* INTERNAL */
		otel_trace::SpanKind::kServer,   /* SERVER */
		otel_trace::SpanKind::kClient,   /* CLIENT */
		otel_trace::SpanKind::kProducer, /* PRODUCER */
		otel_trace::SpanKind::kConsumer, /* CONSUMER */
	};

	/***
	 * Testing is possible in this way because the mapping of
	 * otelc_span_kind_t to span_kind_map is one-to-one.
	 */
	if (!OTELC_IN_RANGE(kind, 0, OTELC_TABLESIZE_1(span_kind_map)))
		OTEL_TRACER_ERETURN_PTR("Invalid span kind: %d", kind);
	span_options.kind = span_kind_map[kind];

	/* Resolve the parent context from a span, span context, or runtime. */
	if (!OTEL_NULL(parent_span)) {
		const auto handle = OTEL_SPAN_HANDLE(parent_span);
		if (OTEL_NULL(handle))
			OTEL_TRACER_ERETURN_PTR("Invalid parent span");

		parent_maybe = handle->context;
		if (OTEL_NULL(parent_maybe))
			OTEL_TRACER_ERETURN_PTR("Unable to get parent span context");
	}
	else if (!OTEL_NULL(parent_context)) {
		const auto handle = OTEL_SPAN_CONTEXT_HANDLE(parent_context);
		if (OTEL_NULL(handle))
			OTEL_TRACER_ERETURN_PTR("Invalid parent span context");

		parent_maybe = handle->context;
		if (OTEL_NULL(parent_maybe))
			OTEL_TRACER_ERETURN_PTR("Unable to get parent span context");
	} else {
#ifdef OTELC_USE_RUNTIME_CONTEXT
		parent_maybe = otel::make_shared_nothrow<otel_context::Context>(otel_context::RuntimeContext::GetCurrent());
#else
		parent_maybe = otel::make_shared_nothrow<otel_context::Context>(otel_context::Context{});
#endif
		if (OTEL_NULL(parent_maybe))
			OTEL_TRACER_ERETURN_PTR("Unable to get current context");
	}

	span_options.parent = *parent_maybe;

	/***
	 * Build the links vector before allocating the span so that link
	 * resolution errors do not require span cleanup.
	 */
	using otel_link_attrs_t = std::map<std::string, otel_attribute_value>;
	using otel_link_entry_t = std::pair<otel_trace::SpanContext, otel_link_attrs_t>;

	std::vector<otel_link_entry_t> links_vec{};

	/* Populate the links vector, validating each entry. */
	if (!OTEL_NULL(links) && (links_len > 0)) {
		try {
			OTEL_DBG_THROW();
			links_vec.reserve(links_len);
		}
		OTEL_CATCH_ERETURN( , OTEL_TRACER_ERETURN_PTR, "Unable to allocate links vector")

		for (size_t i = 0; i < links_len; i++) {
			otel_link_attrs_t link_attr{};
			auto              link_ctx = otel_trace::SpanContext::GetInvalid();

			if (!OTEL_NULL(links[i].span) && !OTEL_NULL(links[i].context))
				OTEL_TRACER_ERETURN_PTR("Link[%zu]: span and context are mutually exclusive", i);
			else if (OTEL_NULL(links[i].span) && OTEL_NULL(links[i].context))
				OTEL_TRACER_ERETURN_PTR("Link[%zu]: one of span or context must be specified", i);
			else if (!OTEL_NULL(links[i].span)) {
				const auto lh = OTEL_SPAN_HANDLE(links[i].span);
				if (OTEL_NULL(lh))
					OTEL_TRACER_ERETURN_PTR("Link[%zu]: invalid span", i);

				link_ctx = lh->span->GetContext();
			}
			else {
				const auto ch = OTEL_SPAN_CONTEXT_HANDLE(links[i].context);
				if (OTEL_NULL(ch))
					OTEL_TRACER_ERETURN_PTR("Link[%zu]: invalid span context", i);

				link_ctx = otel_trace::GetSpan(*(ch->context))->GetContext();
			}

			if (!OTEL_NULL(links[i].kv) && (links[i].kv_len > 0))
				for (size_t j = 0; j < links[i].kv_len; j++)
					OTEL_VALUE_ADD(_PTR, link_attr, emplace, links[i].kv[j].key, &(links[i].kv[j].value), &(tracer->err), "Unable to add link attribute");

			try {
				OTEL_DBG_THROW();
				links_vec.emplace_back(link_ctx, std::move(link_attr));
			}
			OTEL_CATCH_ERETURN( , OTEL_TRACER_ERETURN_PTR, "Unable to add link entry")
		}
	}

	/* Allocating memory for the span. */
	if (OTEL_NULL(retptr = otel_span_new(tracer)))
		OTEL_TRACER_ERETURN_PTR(OTEL_ERROR_MSG_ENOMEM("span"));

	otel_nostd::shared_ptr<otel_trace::Span> span_maybe{};

	if (links_vec.empty()) {
		span_maybe = tracer_ptr->StartSpan(operation_name, span_options);
	} else {
		const std::initializer_list<std::pair<otel_nostd::string_view, otel_attribute_value>> empty_attr{};

		span_maybe = tracer_ptr->StartSpan(operation_name, empty_attr, links_vec, span_options);
	}

	/* Handle span creation failure or initialize the new span. */
	if (OTEL_NULL(span_maybe)) {
		OTEL_TRACER_ERROR("Unable to start new span");

		otel_nolock_span_destroy(&retptr);
	} else {
#ifdef OTELC_USE_RUNTIME_CONTEXT
		/***
		 * Storing the span scope in a map to keep it alive while the
		 * span is active.
		 */
		auto scope = otel::make_shared_nothrow<otel_trace::Scope>(otel_trace::Scope(span_maybe));
		if (OTEL_NULL(scope)) {
			span_maybe->End(otel_trace::EndSpanOptions{});
			otel_nolock_span_destroy(&retptr);

			OTEL_TRACER_ERETURN_PTR(OTEL_ERROR_MSG_ENOMEM("span scope"));
		}
#endif

		/* Create a new context with the span attached to the parent. */
		auto context = otel::make_shared_nothrow<otel_context::Context>(otel_trace::SetSpan(*parent_maybe, span_maybe));
		if (OTEL_NULL(context)) {
			span_maybe->End(otel_trace::EndSpanOptions{});
			otel_nolock_span_destroy(&retptr);

			OTEL_TRACER_ERETURN_PTR(OTEL_ERROR_MSG_ENOMEM("span context"));
		}

		auto span_end = span_maybe;

		/* Allocate the span handle, bundling scope, span, and context. */
#ifdef OTELC_USE_RUNTIME_CONTEXT
		const auto span_handle = new(std::nothrow) otel_span_handle{std::move(scope), std::move(span_maybe), std::move(context)};
#else
		const auto span_handle = new(std::nothrow) otel_span_handle{std::move(span_maybe), std::move(context)};
#endif
		if (OTEL_NULL(span_handle)) {
			span_end->End(otel_trace::EndSpanOptions{});
			otel_nolock_span_destroy(&retptr);

			OTEL_TRACER_ERETURN_PTR(OTEL_ERROR_MSG_ENOMEM("span handle"));
		}

		/* Register the span handle in the shared map. */
		std::pair<std::unordered_map<int64_t, struct otel_span_handle *>::iterator, bool> emplace_status{};
		try {
			OTEL_DBG_THROW();
			emplace_status = OTEL_HANDLE(otel_span, map).emplace(retptr->idx, span_handle);

			if (!emplace_status.second) {
				span_handle->span->End(otel_trace::EndSpanOptions{});

				delete span_handle;
				otel_nolock_span_destroy(&retptr);

				OTEL_TRACER_ERETURN_PTR("Unable to add span: duplicate id");
			}
		}
		OTEL_CATCH_ERETURN({
			if (emplace_status.second)
				OTEL_HANDLE(otel_span, map).erase(retptr->idx);

			span_handle->span->End(otel_trace::EndSpanOptions{});

			delete span_handle;
			otel_nolock_span_destroy(&retptr);
			}, OTEL_TRACER_ERETURN_PTR, "Unable to add span"
		)

		OTEL_HANDLE(otel_span, peak_size) = std::max(OTEL_HANDLE(otel_span, peak_size), OTEL_HANDLE(otel_span, map).size());
	}

	OTEL_DBG_SPAN();

	OTELC_RETURN_PTR(retptr);
}


/***
 * NAME
 *   otel_tracer_start_span - starts a new span
 *
 * SYNOPSIS
 *   static struct otelc_span *otel_tracer_start_span(struct otelc_tracer *tracer, const char *operation_name)
 *
 * ARGUMENTS
 *   tracer         - tracer instance
 *   operation_name - span name
 *
 * DESCRIPTION
 *   Starts a new span (which represents a unit of work or operation).  This
 *   function calls the function otel_tracer_start_span_with_options(), which
 *   offers additional control over span creation.
 *
 * RETURN VALUE
 *   Returns a pointer to the otelc_span structure used to manage the span,
 *   or nullptr in case of an error.
 */
static struct otelc_span *otel_tracer_start_span(struct otelc_tracer *tracer, const char *operation_name)
{
	OTELC_FUNC("%p, \"%s\"", tracer, OTELC_STR_ARG(operation_name));

	OTELC_RETURN_EX(otel_tracer_start_span_with_options(tracer, operation_name, nullptr, nullptr, nullptr, nullptr, OTELC_SPAN_KIND_UNSPECIFIED, NULL, 0), struct otelc_span *, "%p");
}


/***
 * NAME
 *   otel_span_context_add - adds a new span context to the tracer
 *
 * SYNOPSIS
 *   static int otel_span_context_add(struct otelc_tracer *tracer, struct otelc_span_context **span_context, std::shared_ptr<otel_context::Context> &context)
 *
 * ARGUMENTS
 *   tracer       - tracer instance
 *   span_context - address of a pointer to store the new span context
 *   context      - the OpenTelemetry context to be added
 *
 * DESCRIPTION
 *   Creates a new span context and associates it with the provided OpenTelemetry
 *   context.  This is used internally to manage the lifetime and state of span
 *   contexts within the tracer.
 *
 * RETURN VALUE
 *   Returns OTELC_RET_OK on success, or OTELC_RET_ERROR in case of an error.
 */
static int otel_span_context_add(struct otelc_tracer *tracer, struct otelc_span_context **span_context, std::shared_ptr<otel_context::Context> &context)
{
	OTEL_LOCK_TRACER(span_context);

	OTELC_FUNC("%p, %p:%p, <context>", tracer, OTELC_DPTR_ARGS(span_context));

	if (OTEL_NULL(tracer))
		OTELC_RETURN_INT(OTELC_RET_ERROR);
	else if (OTEL_NULL(span_context))
		OTEL_TRACER_ERETURN_INT("Invalid span context");

	if (OTEL_NULL(*span_context = otel_span_context_new()))
		OTEL_TRACER_ERETURN_INT(OTEL_ERROR_MSG_ENOMEM("span context"));

	/* Allocate the span context handle wrapping the extracted context. */
	const auto span_context_handle = new(std::nothrow) otel_span_context_handle{std::move(context)};
	if (OTEL_NULL(span_context_handle)) {
		otel_nolock_span_context_destroy(span_context);

		OTEL_TRACER_ERETURN_INT(OTEL_ERROR_MSG_ENOMEM("span context handle"));
	}

	/* Register the span context handle in the shared map. */
	std::pair<std::unordered_map<int64_t, struct otel_span_context_handle *>::iterator, bool> emplace_status{};
	try {
		OTEL_DBG_THROW();
		emplace_status = OTEL_HANDLE(otel_span_context, map).emplace((*span_context)->idx, span_context_handle);

		if (!emplace_status.second) {
			delete span_context_handle;
			otel_nolock_span_context_destroy(span_context);

			OTEL_TRACER_ERETURN_INT("Unable to add span context: duplicate id");
		}
	}
	OTEL_CATCH_ERETURN({
		if (emplace_status.second)
			OTEL_HANDLE(otel_span_context, map).erase((*span_context)->idx);

		delete span_context_handle;
		otel_nolock_span_context_destroy(span_context);
		}, OTEL_TRACER_ERETURN_INT, "Unable to add span context"
	);

	OTEL_HANDLE(otel_span_context, peak_size) = std::max(OTEL_HANDLE(otel_span_context, peak_size), OTEL_HANDLE(otel_span_context, map).size());

	OTEL_DBG_SPAN_CONTEXT();

	OTELC_RETURN_INT(OTELC_RET_OK);
}


/***
 * NAME
 *   otel_tracer_extract_carrier_cb - callback for extracting carrier data
 *
 * SYNOPSIS
 *   static int otel_tracer_extract_carrier_cb(void *arg, const char *key, const char *value)
 *
 * ARGUMENTS
 *   arg   - user-provided argument, expected to be a carrier container
 *   key   - the key of the carrier entry
 *   value - the value of the carrier entry
 *
 * DESCRIPTION
 *   A callback function used to populate a carrier container with key-value
 *   pairs during context extraction.  This function is invoked for each entry
 *   in the carrier.
 *
 * RETURN VALUE
 *   Returns OTELC_RET_OK on success, or OTELC_RET_ERROR in case of an error.
 */
static int otel_tracer_extract_carrier_cb(void *arg, const char *key, const char *value)
{
	auto *data = OTEL_CAST_REINTERPRET(OTEL_MAP_CARRIER_CONTAINER *, arg);

	OTELC_FUNC("%p, \"%s\", \"%s\"", arg, OTELC_STR_ARG(key), OTELC_STR_ARG(value));

	if (OTEL_NULL(arg) || OTEL_NULL(key) || OTEL_NULL(value))
		OTELC_RETURN_INT(OTELC_RET_ERROR);

	try {
		OTEL_DBG_THROW();
		(void)data->emplace(key, value);
	}
	OTEL_CATCH_RETURN(OTELC_RETURN_INT, OTELC_RET_ERROR, "Unable to add carrier entry")

	OTELC_RETURN_INT(OTELC_RET_OK);
}


/***
 * NAME
 *   otel_tracer_extract_carrier - extracts a span context from a carrier
 *
 * SYNOPSIS
 *   template <template <typename> class CarrierClass, typename ReaderT>
 *   static struct otelc_span_context *otel_tracer_extract_carrier(struct otelc_tracer *tracer, const ReaderT *carrier, const char *carrier_name, const char *dump_label)
 *
 * ARGUMENTS
 *   tracer       - tracer instance
 *   carrier      - the carrier from which to extract the context
 *   carrier_name - human-readable carrier name for error messages
 *   dump_label   - label for text map dump
 *
 * DESCRIPTION
 *   Extracts a span context from the given carrier, allowing for the
 *   propagation of trace context across process boundaries.  This template
 *   consolidates the common logic for text map and HTTP headers extraction.
 *
 * RETURN VALUE
 *   Returns a pointer to the extracted span context on success, or nullptr
 *   on failure.
 */
template <template <typename> class CarrierClass, typename ReaderT>
static struct otelc_span_context *otel_tracer_extract_carrier(struct otelc_tracer *tracer, const ReaderT *carrier, const char *carrier_name, const char *dump_label __maybe_unused)
{
	std::map<std::string, std::string>  carrier_data{};
	struct otelc_span_context          *retptr = nullptr;

	OTELC_FUNC("%p, %p", tracer, carrier);

	if (OTEL_NULL(tracer))
		OTELC_RETURN_PTR(nullptr);
	else if (OTEL_NULL(carrier))
		OTEL_TRACER_ERETURN_PTR("Invalid carrier");

#if !defined(OTELC_USE_THREAD_SHARED_HANDLE) && !defined(OTELC_USE_STATIC_HANDLE)
	if (otel_tracer_handle_init() == OTELC_RET_ERROR)
		OTEL_TRACER_ERETURN_PTR(OTEL_ERROR_MSG_ENOMEM("tracer handle"));
#endif

	OTELC_DBG_CARRIER_READER(OTELC, "carrier", carrier);
	OTELC_TEXT_MAP_DUMP(&(carrier->text_map), dump_label);

	if ((carrier->text_map.count > 0) && (OTEL_NULL(carrier->text_map.key) || OTEL_NULL(carrier->text_map.value)))
		OTEL_TRACER_ERETURN_PTR("Invalid text map carrier data");

	/* Populate carrier data from the text map or via the callback. */
	if (OTEL_NULL(carrier->foreach_key)) {
		for (size_t i = 0; i < carrier->text_map.count; i++)
			try {
				OTEL_DBG_THROW();
				(void)carrier_data.emplace(carrier->text_map.key[i], carrier->text_map.value[i]);
			}
			OTEL_CATCH_ERETURN( , OTEL_TRACER_ERETURN_PTR, "Unable to add carrier entry")
	} else {
		const int rc = carrier->foreach_key(OTEL_CAST_TYPEOF(carrier, carrier), otel_tracer_extract_carrier_cb, &carrier_data);
		if (rc == OTELC_RET_ERROR)
			OTEL_TRACER_ERETURN_PTR("Unable to add a key-value pair to %s carrier", carrier_name);
	}

	/* Extract the context from the carrier using the global propagator. */
	const CarrierClass<std::map<std::string, std::string>> map_carrier(carrier_data);
#ifndef OTELC_USE_RUNTIME_CONTEXT
	otel_context::Context rt_context{};
#else
	auto       rt_context = otel_context::RuntimeContext::GetCurrent();
#endif
	const auto propagator = otel_context::propagation::GlobalTextMapPropagator::GetGlobalPropagator();
	auto       context    = otel::make_shared_nothrow<otel_context::Context>(propagator->Extract(map_carrier, rt_context));
	if (OTEL_NULL(context))
		OTEL_TRACER_ERETURN_PTR("Unable to allocate memory for %s context", carrier_name);

	OTELC_DBG_IFDEF((void)map_carrier.Keys(nullptr), );

#ifndef OTELC_USE_COMPOSITE_PROPAGATOR
	/* If map_carrier contains baggage, it is added to the context. */
	otel_baggage::propagation::BaggagePropagator baggage_propagator;
	context = otel::make_shared_nothrow<otel_context::Context>(baggage_propagator.Extract(map_carrier, *context));
	if (OTEL_NULL(context))
		OTEL_TRACER_ERETURN_PTR(OTEL_ERROR_MSG_ENOMEM("baggage context"));
#endif

	(void)otel_span_context_add(tracer, &retptr, context);

	OTELC_RETURN_PTR(retptr);
}


/***
 * NAME
 *   otel_tracer_extract_text_map - extracts a span context from a text map carrier
 *
 * SYNOPSIS
 *   static struct otelc_span_context *otel_tracer_extract_text_map(struct otelc_tracer *tracer, const struct otelc_text_map_reader *carrier)
 *
 * ARGUMENTS
 *   tracer  - tracer instance
 *   carrier - the text map carrier from which to extract the context
 *
 * DESCRIPTION
 *   Extracts a span context from the given text map carrier, allowing for the
 *   propagation of trace context across process boundaries.  This is a key
 *   mechanism for distributed tracing.
 *
 * RETURN VALUE
 *   Returns a pointer to the extracted span context on success, or nullptr
 *   on failure.
 */
static struct otelc_span_context *otel_tracer_extract_text_map(struct otelc_tracer *tracer, const struct otelc_text_map_reader *carrier)
{
	return otel_tracer_extract_carrier<OTEL_MAP_CARRIER, struct otelc_text_map_reader>(tracer, carrier, "a text map", "text_map extract");
}


/***
 * NAME
 *   otel_tracer_extract_http_headers - extracts a span context from HTTP headers
 *
 * SYNOPSIS
 *   static struct otelc_span_context *otel_tracer_extract_http_headers(struct otelc_tracer *tracer, const struct otelc_http_headers_reader *carrier)
 *
 * ARGUMENTS
 *   tracer  - tracer instance
 *   carrier - the HTTP headers carrier from which to extract the context
 *
 * DESCRIPTION
 *   Extracts a span context from the given HTTP headers carrier, which is a
 *   common method for propagating trace context in web applications.
 *
 * RETURN VALUE
 *   Returns a pointer to the extracted span context on success, or nullptr
 *   on failure.
 */
static struct otelc_span_context *otel_tracer_extract_http_headers(struct otelc_tracer *tracer, const struct otelc_http_headers_reader *carrier)
{
	return otel_tracer_extract_carrier<OTEL_HTTP_CARRIER, struct otelc_http_headers_reader>(tracer, carrier, "an HTTP headers", "http_headers extract");
}


/***
 * NAME
 *   otel_tracer_enabled - checks whether the tracer is enabled
 *
 * SYNOPSIS
 *   static int otel_tracer_enabled(struct otelc_tracer *tracer)
 *
 * ARGUMENTS
 *   tracer - tracer instance
 *
 * DESCRIPTION
 *   Queries the underlying tracer to determine whether it is enabled.  Callers
 *   can use this check to skip expensive span setup when the tracer would
 *   discard the data anyway.
 *
 * RETURN VALUE
 *   Returns true if the tracer is enabled, false if it is not,
 *   or OTELC_RET_ERROR in case of an error.
 */
static int otel_tracer_enabled(struct otelc_tracer *tracer)
{
	OTELC_FUNC("%p", tracer);

	if (OTEL_NULL(tracer))
		OTELC_RETURN_INT(OTELC_RET_ERROR);

	auto tracer_ptr = otel_tracer;
	if (OTEL_NULL(tracer_ptr))
		OTEL_TRACER_ERETURN_INT("Invalid tracer");

#if defined(OPENTELEMETRY_ABI_VERSION_NO) && (OPENTELEMETRY_ABI_VERSION_NO >= 2)
	OTELC_RETURN_INT(tracer_ptr->Enabled() ? true : false);
#else
	OTELC_RETURN_INT(true);
#endif
}


/***
 * NAME
 *   otel_tracer_force_flush - forces the export of any buffered spans
 *
 * SYNOPSIS
 *   static int otel_tracer_force_flush(struct otelc_tracer *tracer, const struct timespec *timeout)
 *
 * ARGUMENTS
 *   tracer  - tracer instance
 *   timeout - maximum time to wait, or NULL for no limit
 *
 * DESCRIPTION
 *   Forces the tracer to export all spans that have been collected but not yet
 *   exported.  This is a blocking call that will not return until the export is
 *   complete.  The optional timeout argument limits how long the operation may
 *   block.
 *
 * RETURN VALUE
 *   Returns OTELC_RET_OK on success, or OTELC_RET_ERROR on failure.
 */
static int otel_tracer_force_flush(struct otelc_tracer *tracer, const struct timespec *timeout)
{
	OTEL_PROVIDER_OP(TRACER, tracer, ForceFlush, "Unable to force flush tracer provider");
}


/***
 * NAME
 *   otel_tracer_shutdown - shuts down the underlying tracer provider
 *
 * SYNOPSIS
 *   static int otel_tracer_shutdown(struct otelc_tracer *tracer, const struct timespec *timeout)
 *
 * ARGUMENTS
 *   tracer  - tracer instance
 *   timeout - maximum time to wait, or NULL for no limit
 *
 * DESCRIPTION
 *   Shuts down the underlying tracer provider, flushing any buffered spans and
 *   releasing provider resources.  After shutdown, no further spans will be
 *   exported.  The optional timeout argument limits how long the operation may
 *   block.
 *
 * RETURN VALUE
 *   Returns OTELC_RET_OK on success, or OTELC_RET_ERROR on failure.
 */
static int otel_tracer_shutdown(struct otelc_tracer *tracer, const struct timespec *timeout)
{
	OTEL_PROVIDER_OP(TRACER, tracer, Shutdown, "Unable to shut down tracer provider");
}


/***
 * NAME
 *   otel_tracer_start - initializes and starts the tracer instance
 *
 * SYNOPSIS
 *   static int otel_tracer_start(struct otelc_tracer *tracer)
 *
 * ARGUMENTS
 *   tracer - tracer instance
 *
 * DESCRIPTION
 *   The tracer whose configuration is specified in the OpenTelemetry YAML
 *   configuration file (set by the previous call to the otelc_init() function)
 *   is started.  The function initializes the tracer in such a way that the
 *   following components are initialized individually: exporter, sampler,
 *   processor and finally provider.
 *
 * RETURN VALUE
 *   Returns OTELC_RET_OK on success, or OTELC_RET_ERROR in case of an error.
 */
static int otel_tracer_start(struct otelc_tracer *tracer)
{
	std::unique_ptr<otel_sdk_trace::SpanExporter>  exporter;
	std::unique_ptr<otel_sdk_trace::Sampler>       sampler;
	std::unique_ptr<otel_sdk_trace::SpanProcessor> processor;
	std::unique_ptr<otel_trace::TracerProvider>    provider;
	char                                           scope_name[OTEL_YAML_BUFSIZ];
	int                                            retval = OTELC_RET_ERROR;

	OTELC_FUNC("%p", tracer);

	if (OTEL_NULL(tracer))
		OTELC_RETURN_INT(retval);

	retval = yaml_find(otelc_fyd, &(tracer->err), 1, "OpenTelemetry tracer instrumentation scope", OTEL_YAML_TRACER_PREFIX "/scope_name", scope_name, sizeof(scope_name));
	if (retval < 1)
		OTELC_RETURN_INT(retval);

	tracer->scope_name = OTELC_STRDUP(__func__, __LINE__, scope_name);
	if (OTEL_NULL(tracer->scope_name))
		OTEL_TRACER_ERETURN_INT(OTEL_ERROR_MSG_ENOMEM("scope name"));

	/***
	 * The function initializes the tracer in such a way that the following
	 * components are initialized individually:
	 *   - exporter (SpanExporter)
	 *   - sampler (Sampler)
	 *   - processor (SpanProcessor)
	 *   - provider (TracerProvider)
	 *
	 * Finally, if everything is initialized, set the global trace provider.
	 */
	if ((retval = otel_tracer_exporter_create(tracer, exporter)) == OTELC_RET_ERROR)
		/* Do nothing. */;
	else if ((retval = otel_sampler_create(tracer, sampler)) == OTELC_RET_ERROR)
		/* Do nothing. */;
	else if ((retval = otel_tracer_processor_create(tracer, exporter, processor)) == OTELC_RET_ERROR)
		/* Do nothing. */;
	else if ((retval = otel_tracer_provider_create(tracer, processor, sampler, provider)) != OTELC_RET_ERROR) {
		otel_nostd::shared_ptr<otel_trace::Tracer> tracer_maybe{};

		tracer_maybe = provider->GetTracer(tracer->scope_name, OTELC_SCOPE_VERSION, OTELC_SCOPE_SCHEMA_URL);

		/* Set up the global text map propagator (composite or single). */
#ifdef OTELC_USE_COMPOSITE_PROPAGATOR
		std::vector<std::unique_ptr<otel_context::propagation::TextMapPropagator>> propagators{};
		auto http_propagator = std::unique_ptr<otel_context::propagation::TextMapPropagator>{new(std::nothrow) otel_trace::propagation::HttpTraceContext()};
		auto baggage_propagator = std::unique_ptr<otel_context::propagation::TextMapPropagator>{new(std::nothrow) otel_baggage::propagation::BaggagePropagator()};
		if (OTEL_NULL(http_propagator) || OTEL_NULL(baggage_propagator))
			OTEL_TRACER_ERETURN_INT(OTEL_ERROR_MSG_ENOMEM("propagators"));

		try {
			OTEL_DBG_THROW();
			propagators.push_back(std::move(http_propagator));
			propagators.push_back(std::move(baggage_propagator));
		}
		OTEL_CATCH_ERETURN( , OTEL_TRACER_ERETURN_INT, "Unable to add propagator")

		const auto propagator = new(std::nothrow) otel_context::propagation::CompositePropagator(std::move(propagators));
		if (OTEL_NULL(propagator))
			OTEL_TRACER_ERETURN_INT(OTEL_ERROR_MSG_ENOMEM("composite propagator"));

		otel_tracer = std::move(tracer_maybe);
		otel_trace::Provider::SetTracerProvider(std::move(provider));
		otel_context::propagation::GlobalTextMapPropagator::SetGlobalPropagator(otel_nostd::shared_ptr<otel_context::propagation::TextMapPropagator>(propagator));

#else

		const auto propagator = new(std::nothrow) otel_trace::propagation::HttpTraceContext();
		if (OTEL_NULL(propagator))
			OTEL_TRACER_ERETURN_INT(OTEL_ERROR_MSG_ENOMEM("http trace propagator"));

		otel_tracer = std::move(tracer_maybe);
		otel_trace::Provider::SetTracerProvider(std::move(provider));
		otel_context::propagation::GlobalTextMapPropagator::SetGlobalPropagator(otel_nostd::shared_ptr<otel_context::propagation::TextMapPropagator>(propagator));
#endif /* OTELC_USE_COMPOSITE_PROPAGATOR */
	}

	OTELC_DBG_TRACER(OTEL, "tracer", tracer);

	OTELC_RETURN_INT(retval);
}


/***
 * NAME
 *   otel_tracer_destroy - stops the tracer and frees all associated memory
 *
 * SYNOPSIS
 *   static void otel_tracer_destroy(struct otelc_tracer **tracer)
 *
 * ARGUMENTS
 *   tracer - address of a tracer instance pointer to be stopped and destroyed
 *
 * DESCRIPTION
 *   Stops the tracer and releases all resources and memory associated with the
 *   tracer instance.
 *
 * RETURN VALUE
 *   This function does not return a value.
 */
static void otel_tracer_destroy(struct otelc_tracer **tracer)
{
	otel_trace::EndSpanOptions end_options{};
	struct timespec            ts_steady;
	bool                       flag_clear_propagator = false;

	OTELC_FUNC("%p:%p", OTELC_DPTR_ARGS(tracer));

	if (OTEL_NULL(tracer) || OTEL_NULL(*tracer))
		OTELC_RETURN();

	OTELC_DBG_TRACER(OTEL, "tracer", *tracer);

	/***
	 * Clear otel_tracer before provider teardown to prevent concurrent
	 * callers from accessing a tracer that is being destroyed.
	 */
	if (!OTEL_NULL(otel_tracer)) {
		otel_tracer = nullptr;

		flag_clear_propagator = true;
	}

	/***
	 * End any remaining spans before destroying the provider so that the
	 * processor can still export them.
	 */
	(void)clock_gettime(CLOCK_MONOTONIC, &ts_steady);
	end_options.end_steady_time = otel_steady_timestamp(timespec_to_duration(&ts_steady));

	/* Clear span contexts and end all remaining spans. */
#ifdef OTELC_USE_STATIC_HANDLE
	OTEL_HANDLE(otel_span_context, clear_locked());

	OTEL_HANDLE(otel_span, for_each_locked([&](int64_t id __maybe_unused, struct otel_span_handle *handle) {
		if (!OTEL_NULL(handle) && !OTEL_NULL(handle->span)) {
			handle->span->End(end_options);

			OTELC_DBG(DEBUG, "span #%" PRId64 " ended implicitly", id);
		}
	}));

#else

	/* Clear and destroy the span context handle map. */
	if (!OTEL_NULL(otel_span_context)) {
		OTEL_HANDLE(otel_span_context, clear_locked());

		delete otel_span_context;
		otel_span_context = nullptr;
	}

	/* End all remaining spans and destroy the span handle map. */
	if (!OTEL_NULL(otel_span)) {
		OTEL_HANDLE(otel_span, for_each_locked([&](int64_t id __maybe_unused, struct otel_span_handle *handle) {
			if (!OTEL_NULL(handle) && !OTEL_NULL(handle->span)) {
				handle->span->End(end_options);

				OTELC_DBG(DEBUG, "span #%" PRId64 " ended implicitly", id);
			}

			delete otel_span;
			otel_span = nullptr;
		}));
	}
#endif /* OTELC_USE_STATIC_HANDLE */

	/* Reset the global propagator if it was set during initialization. */
	if (flag_clear_propagator) {
		const std::shared_ptr<otel_context::propagation::TextMapPropagator> none;
		otel_context::propagation::GlobalTextMapPropagator::SetGlobalPropagator(none);
	}

	otel_tracer_provider_destroy();
	otel_tracer_exporter_destroy();

	OTELC_SFREE((*tracer)->err);
	OTELC_SFREE((*tracer)->scope_name);
	OTELC_SFREE_CLEAR(*tracer);

	OTELC_RETURN();
}


/***
 * NAME
 *   otel_tracer_new - creates a new tracer instance in an unstarted state
 *
 * SYNOPSIS
 *   static struct otelc_tracer *otel_tracer_new(void)
 *
 * ARGUMENTS
 *   This function takes no arguments.
 *
 * DESCRIPTION
 *   Allocates and initializes a new tracer instance in an unstarted state.  The
 *   caller is responsible for starting and eventually destroying the tracer.
 *
 * RETURN VALUE
 *   Returns a pointer to a newly created tracer instance on success, or nullptr
 *   on failure.
 */
static struct otelc_tracer *otel_tracer_new(void)
{
	const static struct otelc_tracer tracer_init = {
		.err                     = nullptr,
		.scope_name              = nullptr,
		.start_span              = otel_tracer_start_span,              /* lock span and span_context */
		.start_span_with_options = otel_tracer_start_span_with_options, /* lock span and span_context */
		.extract_text_map        = otel_tracer_extract_text_map,        /* lock span_context */
		.extract_http_headers    = otel_tracer_extract_http_headers,    /* lock span_context */
		.enabled                 = otel_tracer_enabled,                 /* Locking not required. */
		.force_flush             = otel_tracer_force_flush,             /* Locking not required. */
		.shutdown                = otel_tracer_shutdown,                /* Locking not required. */
		.start                   = otel_tracer_start,                   /* Locking not required. */
		.destroy                 = otel_tracer_destroy,                 /* Locking not required. */
	};
	struct otelc_tracer *retptr = nullptr;

	OTELC_FUNC("");

	if (!OTEL_NULL(retptr = OTEL_CAST_TYPEOF(retptr, OTELC_CALLOC(__func__, __LINE__, 1, sizeof(*retptr)))))
		(void)memcpy(retptr, &tracer_init, sizeof(*retptr));

	OTELC_RETURN_PTR(retptr);
}


/***
 * NAME
 *   otelc_tracer_create - creates and returns a new tracer instance
 *
 * SYNOPSIS
 *   struct otelc_tracer *otelc_tracer_create(char **err)
 *
 * ARGUMENTS
 *   err - address of a pointer to store an error message on failure
 *
 * DESCRIPTION
 *   Allocates and initializes a new tracer instance by calling
 *   otel_tracer_new().  On failure, an error message may be written
 *   to *err if provided.
 *
 * RETURN VALUE
 *   Returns a pointer to a newly created tracer instance on success, or nullptr
 *   on failure.
 */
struct otelc_tracer *otelc_tracer_create(char **err)
{
	struct otelc_tracer *retptr = nullptr;

	OTELC_FUNC("%p:%p", OTELC_DPTR_ARGS(err));

	if (OTEL_NULL(retptr = otel_tracer_new()))
		OTEL_ERETURN_PTR(OTEL_ERROR_MSG_ENOMEM("tracer"));

#if defined(OTELC_USE_THREAD_SHARED_HANDLE) && !defined(OTELC_USE_STATIC_HANDLE)
	if (otel_tracer_handle_init() == OTELC_RET_ERROR) {
		otel_tracer_destroy(&retptr);

		OTEL_ERETURN_PTR(OTEL_ERROR_MSG_ENOMEM("tracer handle"));
	}
#endif

	OTELC_DBG_TRACER(OTEL, "tracer", retptr);

	OTELC_RETURN_PTR(retptr);
}

/*
 * Local variables:
 *  c-indent-level: 8
 *  c-basic-offset: 8
 * End:
 *
 * vi: noexpandtab shiftwidth=8 tabstop=8
 */
